#
# Copyright (C) 2020  ZekerZhayard
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

name: Publication

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.1'
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew.bat build -iS
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: Publish to JCenter
        run: ./gradlew.bat bintrayUpload -iS